1 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: 47f814827db6 looks like a backout, but we couldn't find which revision was backed out.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 47f814827db6 is related to another bug (406451).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 5028e1290b45 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 34ecdab0cfc2 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision b24d1437c6f3 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 23dfc36f99d4 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 95b4aa01923d was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 13cc8a7ee925 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
2 out of 1066
3 out of 1066
4 out of 1066
5 out of 1066
6 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 3b0dafa67477 is related to another bug (1225829).
  revs, backout_comments = get_commits_for_bug(bug)
7 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 78bde999fddd is related to another bug (975782).
  revs, backout_comments = get_commits_for_bug(bug)
8 out of 1066
9 out of 1066
10 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 3127df59e0dc is related to another bug (1110871).
  revs, backout_comments = get_commits_for_bug(bug)
11 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 819833 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
12 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: d0801a6d38dc looks like a backout, but we couldn't find which revision was backed out.
  revs, backout_comments = get_commits_for_bug(bug)
analyze_commits.py:67: UserWarning: Author mycoolclub@yahoo.com could not be found.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
analyze_commits.py:67: UserWarning: Author jmathies@mozilla.com is not in the list of authors on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
13 out of 1066
14 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 5e1dd28ede5d was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 631b3d5d54f4 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
analyze_commits.py:67: UserWarning: Author ehsan@mozilla.com is not in the list of authors on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
15 out of 1066
16 out of 1066
17 out of 1066
18 out of 1066
19 out of 1066
20 out of 1066
21 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 360ab7771e27 is related to another bug (783856).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 67091352b7d2 is related to another bug (681192).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 6fe7dd2f8f57 is related to another bug (752428).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision a86b00fa6bc6 is related to another bug (787564).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 3502d9840d98 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
22 out of 1066
23 out of 1066
24 out of 1066
25 out of 1066
26 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 805197 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
27 out of 1066
28 out of 1066
29 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 1eed7ad9fbb7 is related to another bug (1092915).
  revs, backout_comments = get_commits_for_bug(bug)
analyze_commits.py:67: UserWarning: Reviewer fix could not be found.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
30 out of 1066
analyze_commits.py:67: UserWarning: Author honzab.moz@firemni.cz is not in the list of authors on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
Error with bug 712363: Too many matching authors (honzab.moz@firemni.cz, brian@briansmith.org) found for honzab.moz@firemni.cz
31 out of 1066
32 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: 376dc3151e42 looks like a backout, but we couldn't find which revision was backed out.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 62eaf89ab82f was not found.
  revs, backout_comments = get_commits_for_bug(bug)

33 out of 1066
34 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 820682 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
35 out of 1066
36 out of 1066
37 out of 1066
38 out of 1066
39 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision c608de1b6a53 is related to another bug (751428).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 77bf50b33a05 is related to another bug (716439).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 1d8cb944f7a9 is related to another bug (767965).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 9a1934aec83c is related to another bug (757347).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 2db9df42823d is related to another bug (749957).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 5c07a681371d is related to another bug (767999).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 03cb77f8d75d was not found.
  revs, backout_comments = get_commits_for_bug(bug)
40 out of 1066
41 out of 1066
42 out of 1066
43 out of 1066
44 out of 1066
45 out of 1066
46 out of 1066
47 out of 1066
48 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: 3bd19a1cf4b4 looks like a backout, but we couldn't find which revision was backed out.
  revs, backout_comments = get_commits_for_bug(bug)
analyze_commits.py:67: UserWarning: Author ajones@mozilla.com is not in the list of authors on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
Error with bug 1131638: Too many matching authors (matt.woodrow@gmail.com, ajones@mozilla.com) found for ajones@mozilla.com
49 out of 1066
50 out of 1066
analyze_commits.py:67: UserWarning: Author guilherme.p.gonc@gmail.com could not be found.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
51 out of 1066
52 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 2f9b6bdf63f7 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
53 out of 1066
54 out of 1066
55 out of 1066
56 out of 1066
57 out of 1066
analyze_commits.py:67: UserWarning: Author mozilla@noorenberghe.ca could not be found.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
58 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 204bdc8b929c is related to another bug (1273691).
  revs, backout_comments = get_commits_for_bug(bug)
59 out of 1066
60 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: d75c06f195d2 looks like a backout, but we couldn't find which revision was backed out.
  revs, backout_comments = get_commits_for_bug(bug)
analyze_commits.py:67: UserWarning: Author bugspam.Callek@gmail.com is not in the list of authors on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
Error with bug 771251: Too many matching authors (bugspam.Callek@gmail.com, benjamin@smedbergs.us) found for Callek@gmail.com
61 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision c918ff2f0994 is related to another bug (774216).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 57abb5f70e01 is related to another bug (773262).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 46804c31366b is related to another bug (772307).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision e3676fde39a8 is related to another bug (575294).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision f8d76d32e29b is related to another bug (780661).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 3923d008386d was not found.
  revs, backout_comments = get_commits_for_bug(bug)
62 out of 1066
63 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: 1c1981ecaba8 looks like a backout, but we couldn't find which revision was backed out.
  revs, backout_comments = get_commits_for_bug(bug)
analyze_commits.py:67: UserWarning: Author ryanvm@gmail.com is not in the list of authors on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
Error with bug 810470: Too many matching authors (ryanvm@gmail.com, roc@ocallahan.org) found for ryanvm@gmail.com
64 out of 1066
Error with bug 810082: ('bad handshake: ZeroReturnError()',)
65 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision dafd618c3f52 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 62aa68e8b499 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 2a607cddc4cb was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision f58ce7ac1c7f was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 38efa8f2e56e was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision b2257226899f was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 7a73873e133d was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 2b5753e09a92 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision cf9de5c367a5 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision e416503aea99 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision dfde9d47d8c4 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
66 out of 1066
67 out of 1066
68 out of 1066
69 out of 1066
70 out of 1066
71 out of 1066
72 out of 1066
73 out of 1066
74 out of 1066
75 out of 1066
76 out of 1066
analyze_commits.py:67: UserWarning: Reviewer jrmuziel could not be found.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
77 out of 1066
78 out of 1066
79 out of 1066
80 out of 1066
81 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 822148 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
82 out of 1066
analyze_commits.py:67: UserWarning: Author michal.novotny@gmail.com is not in the list of authors on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
Error with bug 722034: Too many matching authors (michal.novotny@gmail.com, brian@briansmith.org) found for michal.novotny@gmail.com
83 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision fe0abb4decb6 is related to another bug (819731).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 0319dd845d53 is related to another bug (815666).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision c6970a82a686 is related to another bug (819264).
  revs, backout_comments = get_commits_for_bug(bug)
84 out of 1066
analyze_commits.py:67: UserWarning: Author netzen@gmail.com is not in the list of authors on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
Error with bug 791501: Too many matching authors (VYV03354@nifty.ne.jp, netzen@gmail.com) found for netzen@gmail.com
85 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 58605e9a6ea1 is related to another bug (912303).
  revs, backout_comments = get_commits_for_bug(bug)
86 out of 1066
Error with bug 1037424: ('bad handshake: ZeroReturnError()',)
87 out of 1066
88 out of 1066
89 out of 1066
90 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: 3c26af850666 looks like a backout, but we couldn't find which revision was backed out.
  revs, backout_comments = get_commits_for_bug(bug)
91 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 695049af7654 is related to another bug (999580).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 477094180dff was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision ec145c86be71 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 1bc5b733beac was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision c0b8aef8b570 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
92 out of 1066
93 out of 1066
analyze_commits.py:67: UserWarning: Reviewer sewardj could not be found.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
analyze_commits.py:67: UserWarning: Reviewer tglek could not be found.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
94 out of 1066
95 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision cc20208a6eb4 is related to another bug (1034247).
  revs, backout_comments = get_commits_for_bug(bug)
analyze_commits.py:67: UserWarning: Reviewer wmccloskey@mozilla.com is not in the list of reviewers on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
96 out of 1066
97 out of 1066
98 out of 1066
99 out of 1066
100 out of 1066
101 out of 1066
102 out of 1066
analyze_commits.py:67: UserWarning: Reviewer mjronseb could not be found.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
103 out of 1066
104 out of 1066
105 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 1244412 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
106 out of 1066
107 out of 1066
108 out of 1066
109 out of 1066
110 out of 1066
111 out of 1066
analyze_commits.py:67: UserWarning: Reviewer edwin@mozilla.com is not in the list of reviewers on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
112 out of 1066
113 out of 1066
114 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 3efe3f3d2c25 is related to another bug (882111).
  revs, backout_comments = get_commits_for_bug(bug)
115 out of 1066
116 out of 1066
117 out of 1066
118 out of 1066
119 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision f26d6c5a2d93 is related to another bug (767480).
  revs, backout_comments = get_commits_for_bug(bug)
120 out of 1066
Error with bug 1126465: Too many matching authors (bobbyholley@gmail.com, ryanvm@gmail.com) found for ryanvm@gmail.com
121 out of 1066
122 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 4156586d7ac6 is related to another bug (1123979).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 829195e67537 is related to another bug (1133351).
  revs, backout_comments = get_commits_for_bug(bug)
123 out of 1066
124 out of 1066
125 out of 1066
126 out of 1066
127 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: a10dd1a539db looks like a backout, but we couldn't find which revision was backed out.
  revs, backout_comments = get_commits_for_bug(bug)
128 out of 1066
129 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 7d17f2d129e3 is related to another bug (881959).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 58dbd84ae828 is related to another bug (917246).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision fb89f2090779 is related to another bug (881959).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision fe576415129e is related to another bug (881959).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 5e5d5e42f6c2 is related to another bug (881959).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision b221626331b4 is related to another bug (881959).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 2aa38a1a2b06 is related to another bug (881959).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 3d2aac8dc618 is related to another bug (916773).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision ade49a801461 is related to another bug (881959).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 4323508b3412 is related to another bug (917260).
  revs, backout_comments = get_commits_for_bug(bug)
130 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision eb4392d9bc48 is related to another bug (784279).
  revs, backout_comments = get_commits_for_bug(bug)
analyze_commits.py:67: UserWarning: Reviewer doublec could not be found.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
131 out of 1066
132 out of 1066
Connection error:
   url:  https://bugzilla.mozilla.org/rest/user?include_fields=_default&names=bgirard%40mozilla.com
   text:  {"documentation":"http://www.bugzilla.org/docs/tip/en/html/api/","error":true,"code":51,"message":"There is no user named 'bgirard@mozilla.com'. Either you mis-typed the name or that user has not yet registered for a Bugzilla account."}
133 out of 1066
134 out of 1066
135 out of 1066
136 out of 1066
137 out of 1066
Error with bug 1126465: Too many matching authors (bobbyholley@gmail.com, ryanvm@gmail.com) found for ryanvm@gmail.com
138 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 1044975 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
139 out of 1066
analyze_commits.py:67: UserWarning: Author jwwang@mozilla.com is not in the list of authors on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
Error with bug 1159171: Too many matching authors (jwwang@mozilla.com, jyavenard@mozilla.com) found for jwwang@mozilla.com
140 out of 1066
141 out of 1066
142 out of 1066
143 out of 1066
144 out of 1066
145 out of 1066
146 out of 1066
147 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 1a4c6cb31743 is related to another bug (1035773).
  revs, backout_comments = get_commits_for_bug(bug)
148 out of 1066
149 out of 1066
analyze_commits.py:67: UserWarning: Author chris.double@double.co.nz could not be found.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
150 out of 1066
151 out of 1066
Connection error:
   url:  https://bugzilla.mozilla.org/rest/user?include_fields=_default&names=terrence%40mozilla.com
   text:  {"documentation":"http://www.bugzilla.org/docs/tip/en/html/api/","error":true,"code":51,"message":"There is no user named 'terrence@mozilla.com'. Either you mis-typed the name or that user has not yet registered for a Bugzilla account."}
152 out of 1066
153 out of 1066
154 out of 1066
analyze_commits.py:67: UserWarning: Reviewer dao+bmo@mozilla.com is not in the list of reviewers on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
155 out of 1066
156 out of 1066
157 out of 1066
158 out of 1066
159 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 673ca84a9171 is related to another bug (450280).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 673ca84a9171 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
160 out of 1066
161 out of 1066
162 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision e02a02fd1208 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 86a3edf2960d was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 1a8b11ae0f4b was not found.
  revs, backout_comments = get_commits_for_bug(bug)
163 out of 1066
164 out of 1066
165 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: a081cfffeed0 looks like a backout, but we couldn't find which revision was backed out.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision be3cef4b69e3 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision f309dacf4010 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
166 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 1155519 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
167 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 387a5f8b5e4f was not found.
  revs, backout_comments = get_commits_for_bug(bug)
analyze_commits.py:67: UserWarning: Author wjohnston@mozilla.com could not be found.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
analyze_commits.py:67: UserWarning: Reviewer dholbert@mozilla.com is not in the list of reviewers on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
168 out of 1066
169 out of 1066
170 out of 1066
Error with bug 712363: Too many matching authors (honzab.moz@firemni.cz, brian@briansmith.org) found for honzab.moz@firemni.cz
171 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision b4ebefd0f7e3 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
172 out of 1066
analyze_commits.py:67: UserWarning: Reviewer roc@ocallahan.org is not in the list of reviewers on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
173 out of 1066
174 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: 47180a284986 looks like a backout, but we couldn't find which revision was backed out.
  revs, backout_comments = get_commits_for_bug(bug)
175 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision f98f80d2126c is related to another bug (915763).
  revs, backout_comments = get_commits_for_bug(bug)
176 out of 1066
177 out of 1066
178 out of 1066
179 out of 1066
analyze_commits.py:67: UserWarning: Reviewer jocheng@mozilla.com is not in the list of reviewers on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 700583 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
180 out of 1066
181 out of 1066
182 out of 1066
Connection error:
   url:  https://bugzilla.mozilla.org/rest/user?include_fields=_default&names=dmajor%40bugmail.cc
   text:  {"documentation":"http://www.bugzilla.org/docs/tip/en/html/api/","error":true,"code":51,"message":"There is no user named 'dmajor@bugmail.cc'. Either you mis-typed the name or that user has not yet registered for a Bugzilla account."}
183 out of 1066
184 out of 1066
185 out of 1066
186 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 27cc305a5a1a is related to another bug (702739).
  revs, backout_comments = get_commits_for_bug(bug)
187 out of 1066
188 out of 1066
189 out of 1066
190 out of 1066
191 out of 1066
192 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision ccba2b6b092d is related to another bug (946479).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 921be552b22f is related to another bug (943482).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 33e4d9281b5d is related to another bug (947429).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 567d2bba4f97 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
193 out of 1066
194 out of 1066
195 out of 1066
196 out of 1066
197 out of 1066
198 out of 1066
199 out of 1066
200 out of 1066
201 out of 1066
202 out of 1066
203 out of 1066
analyze_commits.py:67: UserWarning: Author jacek@codeweavers.com is not in the list of authors on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
Error with bug 1240589: Too many matching authors (jacek@codeweavers.com, cpeterson@mozilla.com) found for jacek@codeweavers.com
204 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision e497957b79b2 is related to another bug (1103623).
  revs, backout_comments = get_commits_for_bug(bug)
205 out of 1066
Error with bug 810470: Too many matching authors (ryanvm@gmail.com, roc@ocallahan.org) found for ryanvm@gmail.com
206 out of 1066
207 out of 1066
208 out of 1066
209 out of 1066
210 out of 1066
211 out of 1066
212 out of 1066
213 out of 1066
214 out of 1066
215 out of 1066
analyze_commits.py:67: UserWarning: Author kaie@kuix.de is not in the list of authors on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
analyze_commits.py:67: UserWarning: Reviewer wtc@google.com is not in the list of reviewers on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
216 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 1198435 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
217 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 7d8224f00aec is related to another bug (1137336).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision f88b64c38d3d was not found.
  revs, backout_comments = get_commits_for_bug(bug)
218 out of 1066
219 out of 1066
220 out of 1066
221 out of 1066
222 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 824009fbc42f is related to another bug (1183967).
  revs, backout_comments = get_commits_for_bug(bug)
223 out of 1066
224 out of 1066
225 out of 1066
226 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: 8c31e9cebf57 looks like a backout, but we couldn't find which revision was backed out.
  revs, backout_comments = get_commits_for_bug(bug)
227 out of 1066
228 out of 1066
Error with bug 1234422: Too many matching reviewers (masayuki@d-toybox.com, m_kato@ga2.so-net.ne.jp) found for m
229 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 706198 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
230 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 81b505e9a435 is related to another bug (925962).
  revs, backout_comments = get_commits_for_bug(bug)
231 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision cf70852dfbd9 is related to another bug (703029).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision f879c54dffae was not found.
  revs, backout_comments = get_commits_for_bug(bug)
232 out of 1066
233 out of 1066
Error with bug 940907: Uplift either accepted or rejected.
234 out of 1066
235 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: a14914f6351e looks like a backout, but we couldn't find which revision was backed out.
  revs, backout_comments = get_commits_for_bug(bug)
236 out of 1066
237 out of 1066
238 out of 1066
239 out of 1066
240 out of 1066
241 out of 1066
242 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 824395 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
243 out of 1066
244 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 715190 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
245 out of 1066
246 out of 1066
247 out of 1066
248 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: 906c7ac5ac40 looks like a backout, but we couldn't find which revision was backed out.
  revs, backout_comments = get_commits_for_bug(bug)
249 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision c76e6b6d4591 is related to another bug (1149420).
  revs, backout_comments = get_commits_for_bug(bug)
250 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 3c4dc1b74b7f is related to another bug (1125776).
  revs, backout_comments = get_commits_for_bug(bug)
251 out of 1066
analyze_commits.py:67: UserWarning: Author jwalden+fxhelp@mit.edu is not in the list of authors on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
analyze_commits.py:67: UserWarning: Author jwalden+spammybugs@mit.edu is not in the list of authors on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
analyze_commits.py:67: UserWarning: Author jeff.walden@gmail.com is not in the list of authors on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
Error with bug 1021001: Too many matching authors (jwalden+bmo@mit.edu, jwalden+fxhelp@mit.edu, jwalden+spammybugs@mit.edu, jeff.walden@gmail.com) found for jwalden@mit.edu
252 out of 1066
Error with bug 1126465: Too many matching authors (bobbyholley@gmail.com, ryanvm@gmail.com) found for ryanvm@gmail.com
253 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision f47a37f59752 is related to another bug (878932).
  revs, backout_comments = get_commits_for_bug(bug)
254 out of 1066
255 out of 1066
256 out of 1066
257 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision efaf8960a929 is related to another bug (831629).
  revs, backout_comments = get_commits_for_bug(bug)
258 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 711656 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
259 out of 1066
260 out of 1066
261 out of 1066
262 out of 1066
263 out of 1066
264 out of 1066
265 out of 1066
266 out of 1066
267 out of 1066
268 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: 8341dd949e3d looks like a backout, but we couldn't find which revision was backed out.
  revs, backout_comments = get_commits_for_bug(bug)
analyze_commits.py:67: UserWarning: Reviewer nss could not be found.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
269 out of 1066
270 out of 1066
271 out of 1066
272 out of 1066
analyze_commits.py:67: UserWarning: Reviewer false could not be found.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
273 out of 1066
274 out of 1066
275 out of 1066
276 out of 1066
277 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: 6cfd941c49a6 looks like a backout, but we couldn't find which revision was backed out.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 6cfd941c49a6 is related to another bug (776142).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision afd9e75374e8 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
278 out of 1066
279 out of 1066
280 out of 1066
281 out of 1066
282 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 727421 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
283 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: 9bf5e71c5746 looks like a backout, but we couldn't find which revision was backed out.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision a7f80f6408ed is related to another bug (772079).
  revs, backout_comments = get_commits_for_bug(bug)
284 out of 1066
285 out of 1066
286 out of 1066
analyze_commits.py:67: UserWarning: Author justin.lebar+bug@gmail.com is not in the list of authors on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
287 out of 1066
288 out of 1066
289 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 1155432 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
290 out of 1066
291 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 819817 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
292 out of 1066
293 out of 1066
Connection error:
   url:  https://bugzilla.mozilla.org/rest/user?include_fields=_default&names=bgirard%40mozilla.com
   text:  {"documentation":"http://www.bugzilla.org/docs/tip/en/html/api/","error":true,"code":51,"message":"There is no user named 'bgirard@mozilla.com'. Either you mis-typed the name or that user has not yet registered for a Bugzilla account."}
294 out of 1066
295 out of 1066
Error with bug 810470: Too many matching authors (ryanvm@gmail.com, roc@ocallahan.org) found for ryanvm@gmail.com
296 out of 1066
297 out of 1066
298 out of 1066
299 out of 1066
300 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision c85c1d11bd72 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision e17123b5bafd was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 7f904a453bdb was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision cf98685302b6 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 50edbeb8912e was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 6ddbdbd66174 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision e98a176b4e0b was not found.
  revs, backout_comments = get_commits_for_bug(bug)
301 out of 1066
302 out of 1066
303 out of 1066
304 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 1026893 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
305 out of 1066
306 out of 1066
307 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 26f83c4cb81e is related to another bug (858914).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision ebdf97f9ec52 is related to another bug (866675).
  revs, backout_comments = get_commits_for_bug(bug)
308 out of 1066
309 out of 1066
analyze_commits.py:67: UserWarning: Author wkocher@mozilla.com is not in the list of authors on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
310 out of 1066
311 out of 1066
312 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 818220 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
313 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 811763 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
314 out of 1066
315 out of 1066
316 out of 1066
317 out of 1066
analyze_commits.py:67: UserWarning: Author mbrubeck@mozilla.com is not in the list of authors on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
Error with bug 881841: Too many matching authors (kaie@kuix.de, mbrubeck@mozilla.com) found for mbrubeck@mozilla.com
318 out of 1066
319 out of 1066
320 out of 1066
321 out of 1066
322 out of 1066
analyze_commits.py:67: UserWarning: Reviewer tuexen@fh-muenster.de is not in the list of reviewers on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
323 out of 1066
324 out of 1066
325 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 750760 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
326 out of 1066
327 out of 1066
328 out of 1066
329 out of 1066
330 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 9f476b4ac1e1 is related to another bug (762966).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 6b58397ad735 is related to another bug (795262).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision b274e8e3479f is related to another bug (794694).
  revs, backout_comments = get_commits_for_bug(bug)
331 out of 1066
332 out of 1066
333 out of 1066
334 out of 1066
335 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 1205083 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
336 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 1b91cf5c8407 is related to another bug (949475).
  revs, backout_comments = get_commits_for_bug(bug)
337 out of 1066
338 out of 1066
339 out of 1066
340 out of 1066
341 out of 1066
342 out of 1066
343 out of 1066
344 out of 1066
345 out of 1066
346 out of 1066
analyze_commits.py:67: UserWarning: Reviewer luke@mozilla.com is not in the list of reviewers on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
analyze_commits.py:67: UserWarning: Reviewer terrence@mozilla.com is not in the list of reviewers on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
analyze_commits.py:67: UserWarning: Reviewer ehsan@mozilla.com is not in the list of reviewers on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
analyze_commits.py:67: UserWarning: Reviewer jonas@sicking.cc is not in the list of reviewers on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
analyze_commits.py:67: UserWarning: Reviewer jdemooij@mozilla.com is not in the list of reviewers on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
analyze_commits.py:67: UserWarning: Reviewer bobbyholley@gmail.com is not in the list of reviewers on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
analyze_commits.py:67: UserWarning: Reviewer jgilbert@mozilla.com is not in the list of reviewers on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
analyze_commits.py:67: UserWarning: Reviewer bent.mozilla@gmail.com is not in the list of reviewers on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
analyze_commits.py:67: UserWarning: Reviewer jorendorff@mozilla.com is not in the list of reviewers on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
analyze_commits.py:67: UserWarning: Reviewer bbouvier@mozilla.com is not in the list of reviewers on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
analyze_commits.py:67: UserWarning: Reviewer bugs@pettay.fi is not in the list of reviewers on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
analyze_commits.py:67: UserWarning: Reviewer bzbarsky@mit.edu is not in the list of reviewers on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
analyze_commits.py:67: UserWarning: Reviewer nmatsakis@mozilla.com is not in the list of reviewers on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
analyze_commits.py:67: UserWarning: Reviewer josh@joshmatthews.net is not in the list of reviewers on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
analyze_commits.py:67: UserWarning: Reviewer efaustbmo@gmail.com is not in the list of reviewers on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
347 out of 1066
348 out of 1066
349 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: 3aa6bab70380 looks like a backout, but we couldn't find which revision was backed out.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: fe7f450a5435 looks like a backout, but we couldn't find which revision was backed out.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 86f9003c1251 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
350 out of 1066
351 out of 1066
352 out of 1066
353 out of 1066
354 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision be09855c0f5c is related to another bug (626245).
  revs, backout_comments = get_commits_for_bug(bug)
355 out of 1066
356 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 5947680feefb is related to another bug (539356).
  revs, backout_comments = get_commits_for_bug(bug)
357 out of 1066
358 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 3ba2cd25663b is related to another bug (809652).
  revs, backout_comments = get_commits_for_bug(bug)
359 out of 1066
Error with bug 851788: Uplift either accepted or rejected.
360 out of 1066
analyze_commits.py:67: UserWarning: Reviewer philringnalda@gmail.com is not in the list of reviewers on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
361 out of 1066
362 out of 1066
363 out of 1066
364 out of 1066
365 out of 1066
366 out of 1066
367 out of 1066
368 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 5cfc2a0f0054 is related to another bug (1140739).
  revs, backout_comments = get_commits_for_bug(bug)
analyze_commits.py:67: UserWarning: Author philringnalda@gmail.com is not in the list of authors on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
Error with bug 1137470: Too many matching authors (philringnalda@gmail.com, kaie@kuix.de) found for philringnalda@gmail.com
369 out of 1066
370 out of 1066
371 out of 1066
372 out of 1066
373 out of 1066
374 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 716190 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
375 out of 1066
376 out of 1066
377 out of 1066
378 out of 1066
379 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 6009974c1e1c is related to another bug (680164).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: 40f077f9c4a2 looks like a backout, but we couldn't find which revision was backed out.
  revs, backout_comments = get_commits_for_bug(bug)
380 out of 1066
381 out of 1066
382 out of 1066
383 out of 1066
384 out of 1066
385 out of 1066
386 out of 1066
387 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 1301a72b1c39 is related to another bug (795657).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 90857937b601 is related to another bug (800112).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 9f28c28e988f is related to another bug (800157).
  revs, backout_comments = get_commits_for_bug(bug)
388 out of 1066
Error with bug 1120128: Uplift either accepted or rejected.
389 out of 1066
390 out of 1066
391 out of 1066
392 out of 1066
393 out of 1066
394 out of 1066
395 out of 1066
396 out of 1066
397 out of 1066
398 out of 1066
399 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision c84d530c9a51 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
400 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 3acb52b2a6de was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 2f2351cb2579 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
401 out of 1066
402 out of 1066
403 out of 1066
404 out of 1066
405 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: a315b2dfd1b2 looks like a backout, but we couldn't find which revision was backed out.
  revs, backout_comments = get_commits_for_bug(bug)
Error with bug 798510: Too many matching authors (justin.lebar+bug@gmail.com, ehsan@mozilla.com) found for ehsan@mozilla.com
406 out of 1066
407 out of 1066
408 out of 1066
409 out of 1066
410 out of 1066
analyze_commits.py:67: UserWarning: Reviewer philipp@mozilla.com is not in the list of reviewers on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
analyze_commits.py:67: UserWarning: Reviewer jmathies@mozilla.com is not in the list of reviewers on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
411 out of 1066
412 out of 1066
413 out of 1066
414 out of 1066
415 out of 1066
416 out of 1066
417 out of 1066
418 out of 1066
419 out of 1066
420 out of 1066
421 out of 1066
422 out of 1066
423 out of 1066
424 out of 1066
425 out of 1066
426 out of 1066
427 out of 1066
428 out of 1066
429 out of 1066
430 out of 1066
431 out of 1066
432 out of 1066
433 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision d7c0dbcf2a51 is related to another bug (1216723).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 40245af65036 is related to another bug (1227800).
  revs, backout_comments = get_commits_for_bug(bug)
434 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision a568cdcd510d is related to another bug (505120).
  revs, backout_comments = get_commits_for_bug(bug)
435 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 57461a161f93 is related to another bug (855975).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision fef076fed8ab is related to another bug (855975).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 88db24de216c was not found.
  revs, backout_comments = get_commits_for_bug(bug)
436 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 1211568 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
437 out of 1066
438 out of 1066
439 out of 1066
440 out of 1066
441 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 65afb97fc399 is related to another bug (1149702).
  revs, backout_comments = get_commits_for_bug(bug)
442 out of 1066
443 out of 1066
444 out of 1066
445 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 044aec58f5b3 is related to another bug (964929).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 974df2f038ae is related to another bug (959222).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 95c958fa3cf2 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
446 out of 1066
447 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 0d477f84d533 is related to another bug (916602).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision cd0e2e0ef136 is related to another bug (840488).
  revs, backout_comments = get_commits_for_bug(bug)
448 out of 1066
449 out of 1066
450 out of 1066
451 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision eeba341b7e45 is related to another bug (749186).
  revs, backout_comments = get_commits_for_bug(bug)
452 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 6486354e07e4 is related to another bug (879564).
  revs, backout_comments = get_commits_for_bug(bug)
analyze_commits.py:67: UserWarning: Reviewer choller could not be found.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
analyze_commits.py:67: UserWarning: Author brian@briansmith.org is not in the list of authors on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
453 out of 1066
454 out of 1066
455 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 9f11fc87eaa6 is related to another bug (679472).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision f097100df8aa is related to another bug (549468).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision cc1e08803869 is related to another bug (672054).
  revs, backout_comments = get_commits_for_bug(bug)
456 out of 1066
457 out of 1066
analyze_commits.py:67: UserWarning: Reviewer unfocussed could not be found.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
Error with bug 1124400: ('bad handshake: ZeroReturnError()',)
458 out of 1066
459 out of 1066
460 out of 1066
461 out of 1066
462 out of 1066
463 out of 1066
464 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 0d00e58830fe is related to another bug (743247).
  revs, backout_comments = get_commits_for_bug(bug)
465 out of 1066
466 out of 1066
467 out of 1066
468 out of 1066
469 out of 1066
470 out of 1066
471 out of 1066
472 out of 1066
473 out of 1066
474 out of 1066
475 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 5a4bb2092618 is related to another bug (915482).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision bf930e7d61d3 is related to another bug (911786).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 47a8380519cc was not found.
  revs, backout_comments = get_commits_for_bug(bug)
476 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 1145844 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
477 out of 1066
478 out of 1066
479 out of 1066
480 out of 1066
481 out of 1066
482 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 5dd946b1f29b was not found.
  revs, backout_comments = get_commits_for_bug(bug)
483 out of 1066
484 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 9e126e97e347 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
485 out of 1066
486 out of 1066
487 out of 1066
488 out of 1066
489 out of 1066
490 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: 706a4e2b081c looks like a backout, but we couldn't find which revision was backed out.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 706a4e2b081c is related to another bug (967587).
  revs, backout_comments = get_commits_for_bug(bug)
491 out of 1066
492 out of 1066
493 out of 1066
494 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 820652 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
495 out of 1066
496 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision b5ec1de16b81 is related to another bug (1280827).
  revs, backout_comments = get_commits_for_bug(bug)
497 out of 1066
498 out of 1066
499 out of 1066
500 out of 1066
501 out of 1066
502 out of 1066
503 out of 1066
504 out of 1066
505 out of 1066
506 out of 1066
507 out of 1066
508 out of 1066
509 out of 1066
510 out of 1066
511 out of 1066
512 out of 1066
513 out of 1066
Error with bug 722034: Too many matching authors (michal.novotny@gmail.com, brian@briansmith.org) found for michal.novotny@gmail.com
514 out of 1066
515 out of 1066
516 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 670c8a2695b3 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
517 out of 1066
518 out of 1066
519 out of 1066
520 out of 1066
521 out of 1066
522 out of 1066
523 out of 1066
524 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 9989f9ef7b90 is related to another bug (10209).
  revs, backout_comments = get_commits_for_bug(bug)
525 out of 1066
526 out of 1066
527 out of 1066
Error with bug 1166924: Too many matching authors (amarchesini@mozilla.com, wkocher@mozilla.com) found for wkocher@mozilla.com
528 out of 1066
529 out of 1066
530 out of 1066
Error with bug 983208: 
531 out of 1066
532 out of 1066
Error with bug 810470: Too many matching authors (ryanvm@gmail.com, roc@ocallahan.org) found for ryanvm@gmail.com
533 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision b91deae84856 is related to another bug (1057914).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision efe5844c9a5b is related to another bug (1057879).
  revs, backout_comments = get_commits_for_bug(bug)
analyze_commits.py:67: UserWarning: Author cpearce@mozilla.com is not in the list of authors on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
Error with bug 1073805: Too many matching authors (cpearce@mozilla.com, giles@thaumas.net) found for cpearce@mozilla.com
534 out of 1066
535 out of 1066
536 out of 1066
537 out of 1066
538 out of 1066
539 out of 1066
540 out of 1066
Error with bug 1126465: Too many matching authors (bobbyholley@gmail.com, ryanvm@gmail.com) found for ryanvm@gmail.com
541 out of 1066
542 out of 1066
543 out of 1066
544 out of 1066
545 out of 1066
546 out of 1066
analyze_commits.py:67: UserWarning: Reviewer dcamp@mozilla.com is not in the list of reviewers on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
547 out of 1066
548 out of 1066
549 out of 1066
550 out of 1066
551 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 904001 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
552 out of 1066
553 out of 1066
554 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 8edc48525bc6 is related to another bug (900711).
  revs, backout_comments = get_commits_for_bug(bug)
555 out of 1066
556 out of 1066
557 out of 1066
558 out of 1066
559 out of 1066
560 out of 1066
561 out of 1066
562 out of 1066
563 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision cf37257f81d2 is related to another bug (1195162).
  revs, backout_comments = get_commits_for_bug(bug)
564 out of 1066
565 out of 1066
566 out of 1066
567 out of 1066
568 out of 1066
569 out of 1066
570 out of 1066
571 out of 1066
572 out of 1066
573 out of 1066
574 out of 1066
575 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 1155518 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
576 out of 1066
577 out of 1066
578 out of 1066
579 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 783630 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
580 out of 1066
581 out of 1066
582 out of 1066
583 out of 1066
analyze_commits.py:67: UserWarning: Author karlt@mozbugz.karlt.net is not in the list of authors on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
Error with bug 921695: Too many matching authors (jwwang@mozilla.com, karlt@mozbugz.karlt.net) found for karlt+@karlt.net
584 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 717853 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
585 out of 1066
586 out of 1066
587 out of 1066
588 out of 1066
589 out of 1066
590 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision f23efef7f616 is related to another bug (660156).
  revs, backout_comments = get_commits_for_bug(bug)
591 out of 1066
analyze_commits.py:67: UserWarning: Reviewer wjohnston2000@gmail.com is not in the list of reviewers on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
592 out of 1066
593 out of 1066
594 out of 1066
595 out of 1066
596 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 600aee747c40 is related to another bug (892378).
  revs, backout_comments = get_commits_for_bug(bug)
597 out of 1066
598 out of 1066
599 out of 1066
600 out of 1066
601 out of 1066
602 out of 1066
603 out of 1066
604 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 5dd87bff4e11 is related to another bug (203271).
  revs, backout_comments = get_commits_for_bug(bug)
605 out of 1066
606 out of 1066
607 out of 1066
608 out of 1066
609 out of 1066
610 out of 1066
611 out of 1066
612 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision cf209d9bc29c is related to another bug (1267524).
  revs, backout_comments = get_commits_for_bug(bug)
613 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 749143 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
614 out of 1066
615 out of 1066
616 out of 1066
617 out of 1066
618 out of 1066
619 out of 1066
620 out of 1066
621 out of 1066
622 out of 1066
623 out of 1066
analyze_commits.py:67: UserWarning: Reviewer ted@mielczarek.org is not in the list of reviewers on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
analyze_commits.py:67: UserWarning: Reviewer captain could not be found.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 769048 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
624 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 821577 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
625 out of 1066
626 out of 1066
627 out of 1066
628 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision e226e413dd27 is related to another bug (562159).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision e226e413dd27 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
629 out of 1066
630 out of 1066
631 out of 1066
632 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 819772 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
633 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision f74f1e59dc50 is related to another bug (899050).
  revs, backout_comments = get_commits_for_bug(bug)
634 out of 1066
635 out of 1066
636 out of 1066
637 out of 1066
638 out of 1066
639 out of 1066
640 out of 1066
641 out of 1066
642 out of 1066
643 out of 1066
analyze_commits.py:67: UserWarning: Reviewer gsquelart@mozilla.com is not in the list of reviewers on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
644 out of 1066
645 out of 1066
646 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 603008 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
647 out of 1066
648 out of 1066
649 out of 1066
650 out of 1066
651 out of 1066
652 out of 1066
653 out of 1066
654 out of 1066
655 out of 1066
656 out of 1066
657 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: 350ba395c507 looks like a backout, but we couldn't find which revision was backed out.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: 581a0260b08b looks like a backout, but we couldn't find which revision was backed out.
  revs, backout_comments = get_commits_for_bug(bug)
658 out of 1066
659 out of 1066
660 out of 1066
661 out of 1066
Error with bug 792106: Uplift either accepted or rejected.
662 out of 1066
663 out of 1066
664 out of 1066
665 out of 1066
666 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: 0c8faa128dff looks like a backout, but we couldn't find which revision was backed out.
  revs, backout_comments = get_commits_for_bug(bug)
analyze_commits.py:67: UserWarning: Author dholbert@mozilla.com is not in the list of authors on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
Error with bug 1072780: Too many matching authors (rjesup@jesup.org, dholbert@mozilla.com) found for dholbert@cs.stanford.edu
667 out of 1066
668 out of 1066
669 out of 1066
670 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: 97bef33bf606 looks like a backout, but we couldn't find which revision was backed out.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 97bef33bf606 is related to another bug (750551).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 14aa9de6287f is related to another bug (715761).
  revs, backout_comments = get_commits_for_bug(bug)
671 out of 1066
672 out of 1066
673 out of 1066
674 out of 1066
675 out of 1066
676 out of 1066
677 out of 1066
678 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 1132572 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
679 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 1a1a66376625 is related to another bug (1123507).
  revs, backout_comments = get_commits_for_bug(bug)
680 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision cfdf675266b2 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision c5a9a439d72c was not found.
  revs, backout_comments = get_commits_for_bug(bug)
681 out of 1066
682 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 792541 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
683 out of 1066
684 out of 1066
685 out of 1066
686 out of 1066
Connection error:
   url:  https://bugzilla.mozilla.org/rest/user?include_fields=_default&names=bgirard%40mozilla.com
   text:  {"documentation":"http://www.bugzilla.org/docs/tip/en/html/api/","error":true,"code":51,"message":"There is no user named 'bgirard@mozilla.com'. Either you mis-typed the name or that user has not yet registered for a Bugzilla account."}
687 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision b4a63a0b90c2 is related to another bug (778420).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 89ea9764f9e9 is related to another bug (778495).
  revs, backout_comments = get_commits_for_bug(bug)
688 out of 1066
689 out of 1066
690 out of 1066
691 out of 1066
692 out of 1066
Error with bug 815783: Uplift either accepted or rejected.
693 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 1119019 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
694 out of 1066
695 out of 1066
696 out of 1066
697 out of 1066
698 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 4d6a52c5fb75 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 21aab02fb41c was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 55dba2167b36 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 7cf7a6ea28c2 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 73c2707c4f60 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
Error with bug 1098126: Too many matching authors (ajones@mozilla.com, karlt@mozbugz.karlt.net) found for karlt+@karlt.net
699 out of 1066
700 out of 1066
analyze_commits.py:67: UserWarning: Author doug.turner@gmail.com is not in the list of authors on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
Error with bug 1156063: Too many matching authors (bent.mozilla@gmail.com, doug.turner@gmail.com) found for doug.turner@gmail.com
701 out of 1066
702 out of 1066
analyze_commits.py:67: UserWarning: Author padenot@mozilla.com is not in the list of authors on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
703 out of 1066
704 out of 1066
705 out of 1066
706 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 3e19dec4264f is related to another bug (857623).
  revs, backout_comments = get_commits_for_bug(bug)
707 out of 1066
708 out of 1066
709 out of 1066
710 out of 1066
711 out of 1066
712 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision e6f113c83095 is related to another bug (741295).
  revs, backout_comments = get_commits_for_bug(bug)
Connection error:
   url:  https://bugzilla.mozilla.org/rest/user?include_fields=_default&names=dmajor%40bugmail.cc
   text:  {"documentation":"http://www.bugzilla.org/docs/tip/en/html/api/","error":true,"code":51,"message":"There is no user named 'dmajor@bugmail.cc'. Either you mis-typed the name or that user has not yet registered for a Bugzilla account."}
713 out of 1066
714 out of 1066
715 out of 1066
716 out of 1066
Connection error:
   url:  https://bugzilla.mozilla.org/rest/user?include_fields=_default&names=dmajor%40bugmail.cc
   text:  {"documentation":"http://www.bugzilla.org/docs/tip/en/html/api/","error":true,"code":51,"message":"There is no user named 'dmajor@bugmail.cc'. Either you mis-typed the name or that user has not yet registered for a Bugzilla account."}
Connection error:
   url:  https://bugzilla.mozilla.org/rest/user?include_fields=_default&names=dmajor%40bugmail.cc
   text:  {"documentation":"http://www.bugzilla.org/docs/tip/en/html/api/","error":true,"code":51,"message":"There is no user named 'dmajor@bugmail.cc'. Either you mis-typed the name or that user has not yet registered for a Bugzilla account."}
717 out of 1066
718 out of 1066
719 out of 1066
720 out of 1066
721 out of 1066
722 out of 1066
723 out of 1066
Error with bug 1248913: Too many matching authors (mstange@themasta.com, ryanvm@gmail.com) found for ryanvm@gmail.com
724 out of 1066
725 out of 1066
726 out of 1066
727 out of 1066
728 out of 1066
729 out of 1066
730 out of 1066
731 out of 1066
732 out of 1066
733 out of 1066
734 out of 1066
735 out of 1066
736 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision c99d19bfd6a0 is related to another bug (1149605).
  revs, backout_comments = get_commits_for_bug(bug)
737 out of 1066
738 out of 1066
739 out of 1066
740 out of 1066
741 out of 1066
742 out of 1066
Error with bug 1242904: Uplift either accepted or rejected.
743 out of 1066
analyze_commits.py:67: UserWarning: Reviewer upstream could not be found.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
744 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 5cae5d9ef313 is related to another bug (957693).
  revs, backout_comments = get_commits_for_bug(bug)
745 out of 1066
746 out of 1066
747 out of 1066
748 out of 1066
749 out of 1066
750 out of 1066
analyze_commits.py:67: UserWarning: Reviewer tnikkel@gmail.com is not in the list of reviewers on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
751 out of 1066
752 out of 1066
753 out of 1066
754 out of 1066
755 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 1138391 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
756 out of 1066
757 out of 1066
758 out of 1066
759 out of 1066
analyze_commits.py:67: UserWarning: Reviewer kaie@kuix.de is not in the list of reviewers on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
760 out of 1066
761 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 681ab70f6707 is related to another bug (949334).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 093a4a3a68ca is related to another bug (913734).
  revs, backout_comments = get_commits_for_bug(bug)
762 out of 1066
763 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision ed488f577c84 is related to another bug (733553).
  revs, backout_comments = get_commits_for_bug(bug)
764 out of 1066
765 out of 1066
766 out of 1066
767 out of 1066
768 out of 1066
analyze_commits.py:67: UserWarning: Author wmccloskey@mozilla.com is not in the list of authors on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
Error with bug 831626: Too many matching authors (dvander@alliedmods.net, wmccloskey@mozilla.com) found for wmccloskey@mozilla.com
769 out of 1066
770 out of 1066
771 out of 1066
772 out of 1066
773 out of 1066
774 out of 1066
775 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision a829f51aae56 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 15a8086a2431 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
776 out of 1066
777 out of 1066
778 out of 1066
779 out of 1066
780 out of 1066
781 out of 1066
782 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 1d33725cf167 is related to another bug (782546).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision f8e84de2291e is related to another bug (792314).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 58a4e9501f7e is related to another bug (812368).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision e327e66a027d is related to another bug (793554).
  revs, backout_comments = get_commits_for_bug(bug)
783 out of 1066
784 out of 1066
785 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 9fd8b2adc693 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
786 out of 1066
787 out of 1066
788 out of 1066
789 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 820401 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
790 out of 1066
791 out of 1066
792 out of 1066
793 out of 1066
794 out of 1066
795 out of 1066
796 out of 1066
797 out of 1066
798 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision a20b32f37e7a is related to another bug (495040).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision d30b99cfd933 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision b3a8618f901c was not found.
  revs, backout_comments = get_commits_for_bug(bug)
799 out of 1066
800 out of 1066
801 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 508288a2b62c is related to another bug (918345).
  revs, backout_comments = get_commits_for_bug(bug)
802 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision e6b770b14572 is related to another bug (772510).
  revs, backout_comments = get_commits_for_bug(bug)
803 out of 1066
804 out of 1066
805 out of 1066
806 out of 1066
Connection error:
   url:  https://bugzilla.mozilla.org/rest/user?include_fields=_default&names=dmajor%40bugmail.cc
   text:  {"documentation":"http://www.bugzilla.org/docs/tip/en/html/api/","error":true,"code":51,"message":"There is no user named 'dmajor@bugmail.cc'. Either you mis-typed the name or that user has not yet registered for a Bugzilla account."}
807 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision b9085d8ca22e is related to another bug (987680).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 7248b992c6b2 is related to another bug (991767).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision e2db1c06a933 is related to another bug (988713).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 25306d89bded is related to another bug (989858).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 1003707 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
808 out of 1066
809 out of 1066
810 out of 1066
811 out of 1066
812 out of 1066
813 out of 1066
814 out of 1066
815 out of 1066
816 out of 1066
817 out of 1066
818 out of 1066
819 out of 1066
820 out of 1066
821 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 800f7541fb20 is related to another bug (674212).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision a351ae35f2c4 is related to another bug (683096).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 3db901280232 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
822 out of 1066
823 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision f22f257f7330 is related to another bug (827158).
  revs, backout_comments = get_commits_for_bug(bug)
824 out of 1066
825 out of 1066
826 out of 1066
827 out of 1066
828 out of 1066
829 out of 1066
830 out of 1066
831 out of 1066
832 out of 1066
833 out of 1066
834 out of 1066
835 out of 1066
836 out of 1066
analyze_commits.py:67: UserWarning: Author wtc@google.com is not in the list of authors on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
837 out of 1066
838 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision fb56bd7c0feb was not found.
  revs, backout_comments = get_commits_for_bug(bug)
839 out of 1066
840 out of 1066
841 out of 1066
Connection error:
   url:  https://bugzilla.mozilla.org/rest/user?include_fields=email&include_fields=real_name&names=terrence%40mozilla.com
   text:  {"documentation":"http://www.bugzilla.org/docs/tip/en/html/api/","error":true,"code":51,"message":"There is no user named 'terrence@mozilla.com'. Either you mis-typed the name or that user has not yet registered for a Bugzilla account."}
analyze_commits.py:67: UserWarning: Reviewer woof could not be found.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
842 out of 1066
843 out of 1066
844 out of 1066
845 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision fda65b2f990a is related to another bug (957928).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 62d1670e37d9 is related to another bug (896896).
  revs, backout_comments = get_commits_for_bug(bug)
846 out of 1066
847 out of 1066
848 out of 1066
849 out of 1066
850 out of 1066
851 out of 1066
852 out of 1066
853 out of 1066
854 out of 1066
855 out of 1066
856 out of 1066
857 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 499fd45447a2 is related to another bug (1206076).
  revs, backout_comments = get_commits_for_bug(bug)
858 out of 1066
859 out of 1066
860 out of 1066
861 out of 1066
862 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision be0d3f1de9c2 is related to another bug (807181).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 01123067aa58 is related to another bug (806256).
  revs, backout_comments = get_commits_for_bug(bug)
863 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 71a73815eab4 is related to another bug (418131).
  revs, backout_comments = get_commits_for_bug(bug)
864 out of 1066
865 out of 1066
866 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 759162 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
867 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: d74a924a149b looks like a backout, but we couldn't find which revision was backed out.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: 67a219c9fb12 looks like a backout, but we couldn't find which revision was backed out.
  revs, backout_comments = get_commits_for_bug(bug)
868 out of 1066
869 out of 1066
870 out of 1066
871 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 3044539fec87 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
872 out of 1066
873 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 1127198 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
874 out of 1066
875 out of 1066
876 out of 1066
877 out of 1066
878 out of 1066
879 out of 1066
880 out of 1066
Error with bug 881841: Too many matching authors (kaie@kuix.de, mbrubeck@mozilla.com) found for mbrubeck@mozilla.com
881 out of 1066
Error with bug 1193387: Uplift either accepted or rejected.
882 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision f3e4bb1f935c is related to another bug (1199049).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision bd1eed74e2ec was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 3260a147595a was not found.
  revs, backout_comments = get_commits_for_bug(bug)
883 out of 1066
884 out of 1066
885 out of 1066
886 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision c9c29cc97af0 is related to another bug (838839).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 1407288d820b is related to another bug (852087).
  revs, backout_comments = get_commits_for_bug(bug)
analyze_commits.py:67: UserWarning: Reviewer jmuizelaar@mozilla.com is not in the list of reviewers on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
887 out of 1066
888 out of 1066
889 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 0c8faa128dff is related to another bug (1072780).
  revs, backout_comments = get_commits_for_bug(bug)
890 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision c614dabf94e2 is related to another bug (686323).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 5faaa652594f is related to another bug (660532).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision fec42fae34a7 is related to another bug (454532).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 0352a32fde64 is related to another bug (817276).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: 1322a7cadd56 looks like a backout, but we couldn't find which revision was backed out.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 1322a7cadd56 is related to another bug (814718).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision d469840a370f was not found.
  revs, backout_comments = get_commits_for_bug(bug)
analyze_commits.py:67: UserWarning: Author ajohnson@redneon.com is not in the list of authors on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
Error with bug 717178: Too many matching authors (ajohnson@redneon.com, roc@ocallahan.org) found for ajohnson@redneon.com
891 out of 1066
892 out of 1066
893 out of 1066
894 out of 1066
895 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: 8c521a802625 looks like a backout, but we couldn't find which revision was backed out.
  revs, backout_comments = get_commits_for_bug(bug)
896 out of 1066
897 out of 1066
898 out of 1066
899 out of 1066
900 out of 1066
901 out of 1066
Error with bug 1135541: Too many matching authors (dholbert@mozilla.com, gsquelart@mozilla.com) found for dholbert@cs.stanford.edu
902 out of 1066
903 out of 1066
904 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 1085175 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
905 out of 1066
906 out of 1066
907 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: e63fd4fc05a0 looks like a backout, but we couldn't find which revision was backed out.
  revs, backout_comments = get_commits_for_bug(bug)
analyze_commits.py:67: UserWarning: Author Ms2ger@gmail.com is not in the list of authors on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
Error with bug 772679: Too many matching authors (Ms2ger@gmail.com, roc@ocallahan.org) found for ms2ger@gmail.com
908 out of 1066
909 out of 1066
910 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision ebb4eec0258d is related to another bug (875596).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision e3e70237a47a is related to another bug (854765).
  revs, backout_comments = get_commits_for_bug(bug)
911 out of 1066
912 out of 1066
913 out of 1066
914 out of 1066
915 out of 1066
Error with bug 834741: Too many matching authors (kaie@kuix.de, brian@briansmith.org) found for bsmith@mozilla.com
916 out of 1066
917 out of 1066
918 out of 1066
919 out of 1066
920 out of 1066
921 out of 1066
922 out of 1066
923 out of 1066
924 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 61fb80e560de is related to another bug (934378).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: 9f5ebea82f7e looks like a backout, but we couldn't find which revision was backed out.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 9f5ebea82f7e is related to another bug (937721).
  revs, backout_comments = get_commits_for_bug(bug)
analyze_commits.py:67: UserWarning: Author kaie+oldbugzilla@kuix.de is not in the list of authors on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
Error with bug 898431: Too many matching authors (kaie+oldbugzilla@kuix.de, kaie@kuix.de) found for kaie@kuix.de
925 out of 1066
926 out of 1066
927 out of 1066
928 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision b894118e1c77 is related to another bug (837848).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision d4ce9051566e is related to another bug (837859).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 8f4ec9046b03 is related to another bug (836875).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 1eab3e0d7f53 is related to another bug (831683).
  revs, backout_comments = get_commits_for_bug(bug)
929 out of 1066
930 out of 1066
931 out of 1066
932 out of 1066
933 out of 1066
934 out of 1066
935 out of 1066
936 out of 1066
937 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 710511 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
938 out of 1066
939 out of 1066
940 out of 1066
analyze_commits.py:67: UserWarning: Reviewer auto could not be found.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
941 out of 1066
942 out of 1066
943 out of 1066
Error with bug 1098126: Too many matching authors (ajones@mozilla.com, karlt@mozbugz.karlt.net) found for karlt+@karlt.net
944 out of 1066
945 out of 1066
946 out of 1066
Error with bug 1072780: Too many matching authors (rjesup@jesup.org, dholbert@mozilla.com) found for dholbert@cs.stanford.edu
947 out of 1066
948 out of 1066
949 out of 1066
950 out of 1066
analyze_commits.py:67: UserWarning: Reviewer joshmoz could not be found.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
951 out of 1066
952 out of 1066
953 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 719233 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
954 out of 1066
955 out of 1066
956 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 3785489fa210 is related to another bug (1222405).
  revs, backout_comments = get_commits_for_bug(bug)
957 out of 1066
958 out of 1066
analyze_commits.py:67: UserWarning: Reviewer whitespace could not be found.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
959 out of 1066
960 out of 1066
961 out of 1066
Error with bug 722034: Too many matching authors (michal.novotny@gmail.com, brian@briansmith.org) found for michal.novotny@gmail.com
962 out of 1066
963 out of 1066
964 out of 1066
965 out of 1066
966 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 12d72a30fe94 is related to another bug (633282).
  revs, backout_comments = get_commits_for_bug(bug)
967 out of 1066
968 out of 1066
969 out of 1066
Error with bug 1125970: Too many matching authors (cpearce@mozilla.com, bobbyholley@gmail.com) found for cpearce@mozilla.com
970 out of 1066
971 out of 1066
Error with bug 898431: Too many matching authors (kaie+oldbugzilla@kuix.de, kaie@kuix.de) found for kaie@kuix.de
972 out of 1066
973 out of 1066
974 out of 1066
975 out of 1066
976 out of 1066
977 out of 1066
analyze_commits.py:67: UserWarning: Reviewer ekr@rtfm.com is not in the list of reviewers on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
978 out of 1066
979 out of 1066
980 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 71da07ec8ce3 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 698882 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
981 out of 1066
982 out of 1066
analyze_commits.py:67: UserWarning: Author ffxbld could not be found.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
983 out of 1066
984 out of 1066
985 out of 1066
986 out of 1066
987 out of 1066
988 out of 1066
989 out of 1066
990 out of 1066
991 out of 1066
992 out of 1066
993 out of 1066
994 out of 1066
995 out of 1066
996 out of 1066
997 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision e9c7616c4f72 is related to another bug (308590).
  revs, backout_comments = get_commits_for_bug(bug)
998 out of 1066
Error with bug 712363: Too many matching authors (honzab.moz@firemni.cz, brian@briansmith.org) found for honzab.moz@firemni.cz
999 out of 1066
1000 out of 1066
1001 out of 1066
1002 out of 1066
1003 out of 1066
1004 out of 1066
1005 out of 1066
1006 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 713803 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
1007 out of 1066
1008 out of 1066
1009 out of 1066
1010 out of 1066
1011 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 7f5fad93ef78 is related to another bug (807678).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 959f9da9f85e is related to another bug (767158).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: 4a1188e7f538 looks like a backout, but we couldn't find which revision was backed out.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 4a1188e7f538 is related to another bug (804605).
  revs, backout_comments = get_commits_for_bug(bug)
1012 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 9524b1df278e is related to another bug (908669).
  revs, backout_comments = get_commits_for_bug(bug)
Error with bug 881959: Too many matching authors (ehsan@mozilla.com, padenot@mozilla.com) found for ehsan@mozilla.com
1013 out of 1066
1014 out of 1066
Error with bug 1126465: Too many matching authors (bobbyholley@gmail.com, ryanvm@gmail.com) found for ryanvm@gmail.com
1015 out of 1066
1016 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 1154683 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
1017 out of 1066
1018 out of 1066
1019 out of 1066
1020 out of 1066
1021 out of 1066
1022 out of 1066
1023 out of 1066
analyze_commits.py:67: UserWarning: Author steve@ssinger.info is not in the list of authors on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
Error with bug 1207378: Too many matching authors (steve@ssinger.info, seth.bugzilla@blackhail.net) found for steve@ssinger.info
1024 out of 1066
Error with bug 1258317: Too many matching authors (cyu@mozilla.com, jacek@codeweavers.com) found for jacek@codeweavers.com
1025 out of 1066
1026 out of 1066
1027 out of 1066
1028 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 576bbe43bb64 is related to another bug (753239).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 2e3c67b2d95d is related to another bug (719054).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision ae22909cef5a is related to another bug (774671).
  revs, backout_comments = get_commits_for_bug(bug)
1029 out of 1066
1030 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 42079bb031e1 is related to another bug (486200).
  revs, backout_comments = get_commits_for_bug(bug)
1031 out of 1066
1032 out of 1066
1033 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision b61b7f2e0d0b is related to another bug (888562).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision d42a2a82f3d2 is related to another bug (789919).
  revs, backout_comments = get_commits_for_bug(bug)
1034 out of 1066
1035 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: 76fb1757892d looks like a backout, but we couldn't find which revision was backed out.
  revs, backout_comments = get_commits_for_bug(bug)
1036 out of 1066
1037 out of 1066
1038 out of 1066
1039 out of 1066
1040 out of 1066
1041 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision b8194445b364 is related to another bug (630835).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 654641 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
1042 out of 1066
Error with bug 898431: Too many matching authors (kaie+oldbugzilla@kuix.de, kaie@kuix.de) found for kaie@kuix.de
1043 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 2cd9d6be6dc2 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 2980ed8667f3 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 8c6ea94c7a9e was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision e385645fb787 was not found.
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 904720 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
1044 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 865919 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
1045 out of 1066
Error with bug 717178: Too many matching authors (ajohnson@redneon.com, roc@ocallahan.org) found for ajohnson@redneon.com
1046 out of 1066
1047 out of 1066
1048 out of 1066
1049 out of 1066
1050 out of 1066
1051 out of 1066
1052 out of 1066
analyze_commits.py:67: UserWarning: Reviewer testcase could not be found.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
1053 out of 1066
1054 out of 1066
1055 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 1151821 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
1056 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision bbab21ac3b8c is related to another bug (932080).
  revs, backout_comments = get_commits_for_bug(bug)
1057 out of 1066
1058 out of 1066
analyze_commits.py:67: UserWarning: Author ryan could not be found.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
1059 out of 1066
1060 out of 1066
1061 out of 1066
1062 out of 1066
1063 out of 1066
1064 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:465: UserWarning: Bug 700835 doesn't have a uplift request date.
  info.update(uplift_info(bug, uplift_channel))
1065 out of 1066
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 7c119b50e7aa is related to another bug (793065).
  revs, backout_comments = get_commits_for_bug(bug)
/usr/local/lib/python3.5/dist-packages/libmozdata/patchanalysis.py:390: UserWarning: Revision 65b95ed309b9 is related to another bug (797959).
  revs, backout_comments = get_commits_for_bug(bug)
1066 out of 1066
analyze_commits.py:67: UserWarning: Author roc@ocallahan.org is not in the list of authors on Bugzilla.
  info = patchanalysis.bug_analysis(bug if bug is not None else bug_id, channel)
Error with bug 870941: Too many matching authors (spohl.mozilla.bugs@gmail.com, roc@ocallahan.org) found for robert@ocallahan.org
